name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.ref_name }}-release
  cancel-in-progress: true

jobs:
  release-please:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.main.outputs.version }}
      tag_name: ${{ steps.main.outputs.tag_name }}
      release_created: ${{ steps.main.outputs.release_created }}

    steps:
      - name: release-please-action
        id: main
        uses: googleapis/release-please-action@v4
        with:
          release-type: python
